### ISSUE TITLE
AccessToken.permissions emptied

### ISSUE THREAD

**Issue by homburg** [ParsePlatform/ParseFacebookUtils-Android#9]
Hi

I'm having an issue with verifying the permissions after doing a `ParseFacebookUtils.logInWithReadPermissionsInBackground`. I think it's relevant to this issue: https://github.com/ParsePlatform/ParseUI-Android/issues/51

Is this issue being worked on? Otherwise I'd love to contribute a PR

**Comment by grantland** [comment]
The original issue was permissions being cleared on next app launch, not right after `ParseFacebookUtils.logInWithReadPermissionsInBackground` and was fixed in the latest release.

I just tested `AccessToken.getCurrentAcecssToken` right after `ParseFacebookUtils.logInWithReadPermissionsInBackground`and it contains the correct permissions, could you describe your issue more in depth?

**Comment by homburg** [comment]
Thanks, I'll see if I can reproduce the error in a standalone project.

According to `AccessTokenTracker.onCurrentAccessTokenChanged`, my access token is:
1. initialized correctly (with permissions)
2. set to null
3. recreated with same token but empty permissions set

**Comment by homburg** [comment]
Could not repo, closing

**Comment by swapnilgt** [comment]
I am still facing this issue. What I want to do is to force user to give away his/her email through facebook as it is necessary for our system to work. So, when I accept to give away the requested permissions at first go, I get all the permissions in the payload. But, let's say, I deny giving email at the first go, I only get `public_profile` in my `AccessToken.getPermissions()`. Based on this, I prompt user that the email is required and ask him/her to try again. Now, when I try again and allow to give away the 'email', I get an empty set in `AccessToken.getPermissions()`. So, this is reproducible for me.

**Comment by HIFILEO** [comment]
swapnilgt is right. This is still an issue.
